### ISSUE TITLE
Add Open Source Saturday Badge in README

### ISSUE THREAD

**Issue by ludusrusso** [Schrodinger-Hat/open-source-wrapped#15]
[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)

We work on this project during the OSS Milano last Saturday, the only rule is to add the badge to every PR submitted during the event. But since we do not have a pr I think it's nice to add the badge to the project!

**Comment by TheJoin95** [comment]
Could you add a brief explanation in this issue of the reason behind this, so it will be public and clear, thank you

**Comment by TheJoin95** [comment]
@ludusrusso ping

**Comment by davideimola** [comment]
@TheJoin95 he leaves the explanation in the first message

**Comment by 404answernotfound** [comment]
We can do that, just create a PR for that and merge

**Comment by TheJoin95** [comment]
Sorry, did not see the edit. 
I leave it here as a good first issue then

**Comment by 404answernotfound** [comment]
Anyone up for grab?

**Comment by lucAsC87** [comment]
Hi! I think that's something I can handle even with my newbie skills. :)
