### ISSUE TITLE
Create a developer app on Github

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/open-source-wrapped#2]
We need it in order to retrieve the data.

We can check if we can retrieve the data by curl the github.com website, but I'm not sure if the policy allow us to do it

**Comment by 404answernotfound** [comment]
Can you take this @nicpuppa ?

**Comment by abe-101** [comment]
In the settings for Schrodinger-Hat org we need to give permissions to create a Personal access tokens
https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization

**Comment by abe-101** [comment]
I think we'd need to create a github app for this

![image](https://user-images.githubusercontent.com/82916197/206924862-e1e75b22-0ab9-4fd3-9167-9cc31e192330.png)
https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-a-github-app

**Comment by davideimola** [comment]
I have already created a GitHub App under the organization but we have to decide which things a user must do in order to retrieve its information.
Perhaps it may be possible to use PAT instead of GitHub Apps.
