### ISSUE TITLE
Add redirect after signin to /wrapped/[username] and check if session.username eq param.username

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/open-source-wrapped#22]
After github signin we need to redirect the user to /wrapped/[username] and check if it's the actual user from session and path.
Otherwise 404.

We need this for sharing on social media

We can eventually add a /redirect page just to get the github data, init session and redirect the user to /wrapped/[username] or 404

**Comment by nicpuppa** [comment]
@TheJoin95 is it ok for you if, instead of redirect the user to 404 (we don't have a landing page), we redirect user to homepage instead ?

**Comment by 404answernotfound** [comment]
> @TheJoin95 is it ok for you if, instead of redirect the user to 404 (we don't have a landing page), we redirect user to homepage instead ?

i think it makes sense. What you guys think?
