### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by nicpuppa** [Schrodinger-Hat/open-source-wrapped#32]
![favicon-32x32](https://user-images.githubusercontent.com/72783243/207871219-9a5a24fc-b64a-4ff8-b1d3-c61d70cea7b7.png)

**Comment by Rishav1707** [comment]
Which icon do I have to add in the favicon icon?? @nicpuppa

**Comment by nicpuppa** [comment]
@Rishav1707 I upload the favicon in the description, thank you!

**Comment by Rishav1707** [comment]
Ok
