### ISSUE TITLE
Create a landing page for the project where to fill the data to generate the image

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/open-source-wrapped#4]
We need to create a landing page that may render a few project information.

Through the landing page, you can also generate your wrapped image.

We must decide which solution is better.

- use a Login with GitHub button (as already present in main) and use it to retrieve the user who wants to generate the image
- use a form where the user may be able to insert its GitHub handle to receive its image

**Comment by davideimola** [comment]
I'd prefer the first solution imho
